# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_assign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
