# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_assign', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
