# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_assign', '0003_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
