# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_assign', '0004_services_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
