# Generated by Django 2.2.6 on 2019-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_assign', '0005_auto_20191023_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
