# Generated by Django 2.2.6 on 2019-10-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_assign', '0006_auto_20191028_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='plate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mechanic_assign.car'),
            preserve_default=False,
        ),
    ]
