# Generated by Django 2.2.6 on 2019-10-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_assign', '0007_booking_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='plate',
        ),
    ]
